language: ruby
rvm:
  - 1.9.2

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role etail SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database etail_test;' -U etail postgres"
  - "sh -e /etc/init.d/xvfb start"

env:
  - DISPLAY=:99.0

script: "bundle exec rake db:migrate && bundle exec rspec spec && bundle exec cucumber"

branches:
  only:
    - master
